pipeline {
   agent {
       docker {
           image 'python:3.10'
           args '-v /var/run/docker.sock:/var/run/docker.sock'
       }
   }
   environment {
       DOCKERHUB_CREDENTIALS = credentials('dockerhub-cred')
       DOCKER_REGISTRY = 'olego700'
       REPO_NAME = 'fe-exam'  //### IMAGE NAME -  Change to 'be-exam' WHEN creating the backend pipeline
       IMAGE_TAG = "${env.BUILD_NUMBER}"
   }
   stages {
        stage('Setup Docker') {
            steps {
                sh 'apt-get update && apt-get install -y docker.io'
            }
        }
       stage('Clone Repository') {
           steps {
               git branch: 'workshop/argo-jenkins-exam', url: 'https://github.com/olego700/devopshift-welcome.git'
           }
       }
       stage('Lint & Security Scan') {
            parallel {
                stage('Flake8 Linting') {
                    steps {
                        sh 'pip install flake8'
                        sh 'flake8 . || true' 
                    }
                }
                stage('Bandit Security Scan') {
                    steps {
                        sh 'pip install bandit'
                        sh 'bandit -r . || true'
                    }
                }
            }
        }
        stage('Install Dependencies'){
            steps{
                sh 'pip install -r exam-code/docker/fe/requirements.txt'
            }
        }
        stage('Build Docker Image') {
            steps {
                sh "docker build -t olego700/your-app:$BUILD_NUMBER"
                sh "docker tag olego700/your-app:$BUILD_NUMBER olego700/your-app:latest"
            }
        }
        stage('Run Tests in Container') {
            steps {
                sh " docker run --rm olego700/your-app:$BUILD_NUMBER pytest tests/"
            }
        }
        stage('Integration Test with Docker Compose') {
            steps {
                sh 'docker-compose up -d'
                sh 'sleep 10'
                sh 'curl -f http://localhost:5002 || exit 1'  // Adjust for backend if needed
                sh 'docker-compose down'
            }
        }
        stage('Push to Docker Hub') {
            steps {
                sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
                sh "docker push ${DOCKER_REGISTRY}/${REPO_NAME}:${IMAGE_TAG}"
                sh "docker push ${DOCKER_REGISTRY}/${REPO_NAME}:latest"
            }
        }
    }   
}